Tillerino/Tillerinobot

tillerinobot/src/main/java/tillerino/tillerinobot/UserDataManager.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Spanish.java

Spanish translation with no grammar and spelling mistakes and proper Spanish interrogation mark usage.

Spanish translation by sibchil.

---

tillerinobot/src/main/java/tillerino/tillerinobot/lang/Tsundere.java

just reddit and twitter links.

hyperlinks and updated twitter

---

tillerinobot/src/main/java/tillerino/tillerinobot/lang/Portuguese.java

mistype corrections and added hyperlinks to user profiles, twitter and reddit.

PT-BR update + added hyperlinks

---

tillerinobot/src/main/java/tillerino/tillerinobot/RecommendationsManager.java
tillerinobot/src/test/java/tillerino/tillerinobot/RecommendationsManagerTest.java

Adds #49 
This is the same as the patch linked in that thread.

Alias "nc" to the DoubleTime mod in recommendations

---

tillerinobot/src/main/java/tillerino/tillerinobot/predicates/MapLength.java
tillerinobot/src/main/java/tillerino/tillerinobot/predicates/PredicateParser.java

Adding a filter for Map Length.

Map Length Filter

---

tillerinobot/src/main/java/tillerino/tillerinobot/handlers/NPHandler.java
tillerinobot/src/test/java/tillerino/tillerinobot/LocalConsoleTillerinobot.java

I also added something (probably not that fancy) stuff to LocalConsoleTillerinobot to test both np-use-cases, with http and with https. Feel free to think that's bullshit, and I'll remove them ^^

NPHandler now also accepts https-urls

---

tillerinobot/src/main/java/tillerino/tillerinobot/lang/Portuguese.java

Portuguese.java apiTimeoutException() strings

---

tillerinobot/src/main/java/tillerino/tillerinobot/lang/Hebrew.java

Also added https to the reddit link and added github profile

Better explanation for unknown beatmaps

---

tillerinobot/src/main/java/tillerino/tillerinobot/lang/Spanish.java

Corrected and translated Spanish

Translate Spanish.java

---

tillerinobot/.gitignore
tillerinobot/src/main/java/tillerino/tillerinobot/lang/ChineseTraditional.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Czech.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Dansk.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Deutsch.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Farsi.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Francais.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Greek.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Hebrew.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Hungarian.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Italiano.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Japanese.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Korean.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Lithuanian.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Nederlands.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Polski.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Portuguese.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/PortuguesePortugal.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Romana.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Russian.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Spanish.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Svenska.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Tsundere.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Turkish.java

and yes, I use IntelliJ, so I added some things to .gitignore.
Also the quality of the new dutch translation is probably shit, but better than nothing ^^

the new faq-entry also in the other languages + update dutch translation

---

tillerinobot/src/main/java/tillerino/tillerinobot/lang/Spanish.java

i cant force test to do apiTimeoutException, but it compiles and passes the tests, so afaik its all gud :P

apiTimeoutException in spanish is now working

---

tillerinobot/src/main/java/tillerino/tillerinobot/IRCBot.java
tillerinobot/src/main/java/tillerino/tillerinobot/handlers/FixIDHandler.java
tillerinobot/src/test/java/tillerino/tillerinobot/TestBackend.java

this should do it i guess, shoot me if i did something wrong Keepo

!fixid implementation

---

tillerinobot/src/main/java/tillerino/tillerinobot/BotAPIServer.java
tillerinobot/src/main/java/tillerino/tillerinobot/rest/UserByIdService.java
tillerinobot/src/test/java/tillerino/tillerinobot/TestBackend.java

so we can fix id's with it ;)
also "testkey" is now a valid api-key for the test-api-server so i could test key-stuff :stuck_out_tongue:

implemented UserByIdService

---

README.md

probably looks better this way

Live discord icon and link

---

tillerinobot/src/main/java/tillerino/tillerinobot/BeatmapMeta.java

Not sure if this needs altered/expanded unit tests, if so I probably should be able to add them (I think..), or you can add them :stuck_out_tongue:

Added OD to BeatmapMeta. Fixes #75

---

tillerinobot/src/main/java/tillerino/tillerinobot/lang/Bulgarian.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/ChineseTraditional.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Czech.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Dansk.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Default.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Deutsch.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Farsi.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Francais.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Greek.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Hebrew.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Hungarian.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Italiano.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Japanese.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Korean.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Lithuanian.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Nederlands.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Polski.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Portuguese.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/PortuguesePortugal.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Romana.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Russian.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Spanish.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Svenska.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Turkish.java
tillerinobot/src/test/java/tillerino/tillerinobot/lang/HebrewTest.java

Lets at least give a proper error message till it is fixed for real :D

---

tillerinobot/src/main/java/tillerino/tillerinobot/lang/Romana.java

Added the last 3 lines for the romanian translation.

Romana.java

---

tillerinobot/src/main/java/tillerino/tillerinobot/UserDataManager.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Norwegian.java

Transelation for Tillerinobot in Norwegian

Norwegian.java

---

tillerinobot/src/main/java/tillerino/tillerinobot/lang/Indonesian.java

They were already can be understandable, but its kinda make some people misunderstood things, so, just polish it so it doesn't make people misunderstood the sentence
And about the credits, i don't really sure about it, since i juat polish things.
_but if you want me to go into the credits, my osu! Nickname is Error-_

Polishing some words, and sentences at Indonesian language

---

tillerinobot/src/main/java/tillerino/tillerinobot/handlers/OsuTrackHandler.java
tillerinobot/src/test/java/tillerino/tillerinobot/IRCBotTest.java

cuz im fucking stupid and didnt write unit tests on time
Even the unit tests I had eventually were wrong :cry: :cry: :cry: :cry: :cry: :cry:

Fix osu!track handler, rank update was giving wrong result

---

tillerinobot/src/main/java/tillerino/tillerinobot/UserDataManager.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/ChineseSimple.java

add lang ChineseSimple

---

docs/swagger/swagger.yml
tillerinobot/src/main/java/tillerino/tillerinobot/rest/BeatmapInfoService.java

I don't use java often so forgive my stupid mistakes
I think a double[] like that is fine but maybe it should be a list or something?

Support for multiple requested accs in api

---

tillerinobot/src/main/java/tillerino/tillerinobot/BeatmapMeta.java
tillerinobot/src/main/java/tillerino/tillerinobot/diff/PercentageEstimates.java
tillerinobot/src/main/java/tillerino/tillerinobot/diff/PercentageEstimatesImpl.java
tillerinobot/src/main/java/tillerino/tillerinobot/handlers/AccHandler.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/TsundereEnglish.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/TsundereGerman.java
tillerinobot/src/main/java/tillerino/tillerinobot/rest/BeatmapInfoService.java
tillerinobot/src/test/java/tillerino/tillerinobot/TestBackend.java
tillerinobot/src/test/java/tillerino/tillerinobot/handlers/AccHandlerTest.java

As discussed in #136.
Implementation *probably* works, but I can't test it since the testbackend-stuff doesnt properly implement `PercentageEstimates`.
Line 102 in `TestBackend.java` for example, did a random thing to make it happy, but its probably not what it should be :stuck_out_tongue:

specify number of 100s/50s in !acc

---

tillerinobot/src/main/java/tillerino/tillerinobot/UserDataManager.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Catalan.java

This language is commonly speaken in Spain and Valencian community but why not translate it to this? uwu

Add Catalan language

---

tillerinobot/src/main/java/tillerino/tillerinobot/lang/Hungarian.java

Note: should I remove the last commit?

Fixed Hungarian translation

---

tillerinobot/src/main/java/tillerino/tillerinobot/lang/Polish.java

I don't know what lang-update branch is, so i made edits in master branch

Fixed some grammar and interpunction errors in Polish translation

---

tillerinobot/src/main/java/tillerino/tillerinobot/lang/Czech.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/LanguageIdentifier.java
tillerinobot/src/main/java/tillerino/tillerinobot/lang/Slovak.java

Translate Slovak.java

---

tillerinobot/pom.xml

Github security thing triggered

Bump dependencies

---

tillerinobot/src/main/java/tillerino/tillerinobot/handlers/NPHandler.java

this time should be final, see https://github.com/ppy/osu-stable-issues/issues/752

the /np link changed again

---

tillerinobot/src/main/java/tillerino/tillerinobot/lang/Polish.java

83: "żadnych znaków" -> "żadnych innych znaków" {more sense in Polish}
179: "(...)więc w tym momencie nie mogę nic dla Ciebie zrobić." -> "(...) więc w tym momencie nie mogę Tobie pomóc." {less formal translation}
192: "Zabawne pytanie: (...)." ->  "Takie tam pytanie: (...)." {less formal translation}
(Very) Small adjustments. I even don't think I should be mentioned in GameChatResponse adjustments (l. 160)

Translate polish.java

---

tillerinobot/src/main/java/tillerino/tillerinobot/handlers/OptionsHandler.java
tillerinobot/src/test/java/tillerino/tillerinobot/handlers/OptionsHandlerTest.java

fix bug where `optionalCommentOnLanguage` would be called on the old language instead of the new after setting new language
(also I noticed one test that didnt had the @Test annotation so I added it lol)

set language bug
